package com.mycompany.fypmaven;

import java.awt.KeyboardFocusManager;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.security.SecureRandom;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Work
 */
public class CreateAccountPanel extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccountPanel
     */
    UserAccs user;

    public CreateAccountPanel() {

    }

    public CreateAccountPanel(UserAccs user) {
        initComponents();

        this.user = user;

//        Function to allow remove focus on background click
        getContentPane().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                KeyboardFocusManager.getCurrentKeyboardFocusManager().clearGlobalFocusOwner();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtDescription = new javax.swing.JTextField();
        LblDescription = new javax.swing.JLabel();
        LblUserName = new javax.swing.JLabel();
        TxtUsername = new javax.swing.JTextField();
        LblPassword = new javax.swing.JLabel();
        TxtPassword = new javax.swing.JTextField();
        BtnGeneratePass = new javax.swing.JButton();
        LblURL = new javax.swing.JLabel();
        TxtURL = new javax.swing.JTextField();
        BtnSave = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtDescription.setMinimumSize(new java.awt.Dimension(37, 225));

        LblDescription.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblDescription.setForeground(new java.awt.Color(0, 0, 0));
        LblDescription.setText("Description:");

        LblUserName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblUserName.setForeground(new java.awt.Color(0, 0, 0));
        LblUserName.setText("Username :");

        TxtUsername.setMinimumSize(new java.awt.Dimension(37, 225));

        LblPassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblPassword.setForeground(new java.awt.Color(0, 0, 0));
        LblPassword.setText("Password :");

        TxtPassword.setEnabled(false);

        BtnGeneratePass.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        BtnGeneratePass.setText("Generate Password");
        BtnGeneratePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGeneratePassActionPerformed(evt);
            }
        });

        LblURL.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblURL.setForeground(new java.awt.Color(0, 0, 0));
        LblURL.setText("URL :");

        BtnSave.setLabel("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BtnCancel.setText("Cancel");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LblDescription)
                .addGap(15, 15, 15)
                .addComponent(TxtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LblUserName)
                .addGap(18, 18, 18)
                .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LblPassword)
                .addGap(21, 21, 21)
                .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(BtnGeneratePass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(LblURL)
                .addGap(25, 25, 25)
                .addComponent(TxtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(BtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(LblDescription))
                    .addComponent(TxtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(LblUserName))
                    .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(LblPassword))
                    .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnGeneratePass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(LblURL))
                    .addComponent(TxtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed

        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_BtnCancelActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // Setting of the required variables
        String Username = TxtUsername.getText();
        String Password = TxtPassword.getText();
        String Description = TxtDescription.getText();
        String URL = TxtURL.getText();
        String UserID = user.getUserID();

        //  Data and query required for creating accounts
        Object[] Accdata = {Description, Username, Password, URL, UserID};
        String insertQuery = "INSERT INTO accounts (Description, Username, Password, URL, user_id) VALUES (?, ?, ?, ?, ?)";

//          Data required to check if there are any duplicates
        Object[] Data = {Description, UserID};
        String duplicateQuery = "SELECT Description FROM accounts WHERE Description = ? AND user_id = ?";
        
        if(Username.equals("") || Password.equals("") || Description.equals("") || URL.equals("")){
            
             GeneralFunctions.showNotification("Please ensure that all the textboxes are filled in.", "Failed");
        }
        else if (GeneralFunctions.checkDuplicate(Data,  duplicateQuery) == true) {

            GeneralFunctions.showNotification("There is already an account with the same description.", "Failed");

        } else {

            try {

                DB_Connection connection = new DB_Connection();

                connection.getConnection();

                connection.executeQuery(insertQuery, Accdata);

                GeneralFunctions.showNotification("Account saved", "Success");

                Dashboard dashboard = new Dashboard(user);
                dashboard.setVisible(true);

                this.dispose();

            } catch (SQLException ex) {
                Logger.getLogger(RegisterPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_BtnSaveActionPerformed

    private void BtnGeneratePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGeneratePassActionPerformed
        
     String LOWERCASE = "abcdefghijklmnopqrstuvwxyz";
     String UPPERCASE = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
     String DIGITS = "0123456789";
     String SPECIAL_CHARACTERS = "!@#$%^&*()_-+=<>?";
            
     int passwordLength = 20;
        boolean includeUppercase = true;
        boolean includeDigits = true;
        boolean includeSpecialChars = true;

        SecureRandom random = new SecureRandom();
        StringBuilder password = new StringBuilder();

        // Define the character set based on user preferences
        String characters = LOWERCASE;
        if (includeUppercase) characters += UPPERCASE;
        if (includeDigits) characters += DIGITS;
        if (includeSpecialChars) characters += SPECIAL_CHARACTERS;

        // Ensure the password length is at least 8 characters
        passwordLength = Math.max(passwordLength, 8);

        // Generate the password
        for (int i = 0; i < passwordLength; i++) {
            int index = random.nextInt(characters.length());
            password.append(characters.charAt(index));
        }

        String securePassword = password.toString();
        TxtPassword.setText(securePassword);
    
    }//GEN-LAST:event_BtnGeneratePassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccountPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccountPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccountPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccountPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccountPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnGeneratePass;
    private javax.swing.JButton BtnSave;
    private javax.swing.JLabel LblDescription;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblURL;
    private javax.swing.JLabel LblUserName;
    private javax.swing.JTextField TxtDescription;
    private javax.swing.JTextField TxtPassword;
    private javax.swing.JTextField TxtURL;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    // End of variables declaration//GEN-END:variables
}
