package com.mycompany.fypmaven;

import java.awt.KeyboardFocusManager;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Work
 */
public class EditAccountPanel extends javax.swing.JFrame {

    /**
     * Creates new form EditAccountPanel
     */
    UserAccs user;
    String description;

    public EditAccountPanel() {
        initComponents();
    }

    public EditAccountPanel(UserAccs user, String description) {
        initComponents();

        this.user = user;
        this.description = description;
        
//   Data and query required for the reading of the data
        Object[] param = {description, user.getUserID()};
        String query = "SELECT * FROM accounts where description = ? AND user_id = ?";
        String username = null;
        String password = null;
        String URL = null;
        
        try {

            DB_Connection connection = new DB_Connection();

            connection.getConnection();
            
            username = connection.executeReadQuery(query, param, "Username");
            password = connection.executeReadQuery(query, param, "Password");
            URL = connection.executeReadQuery(query, param, "URL");
            this.dispose();

        } catch (SQLException ex) {
            Logger.getLogger(RegisterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        TxtDescription.setText(description);
        TxtUsername.setText(username);
        TxtPassword.setText(password);
        TxtURL.setText(URL);
        
        //        Function to allow remove focus on background click
        getContentPane().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                KeyboardFocusManager.getCurrentKeyboardFocusManager().clearGlobalFocusOwner();
            }
        });

    }

    public static void insertToTextBox() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtDescription = new javax.swing.JTextField();
        LblDescription = new javax.swing.JLabel();
        LblUserName = new javax.swing.JLabel();
        TxtUsername = new javax.swing.JTextField();
        LblPassword = new javax.swing.JLabel();
        TxtPassword = new javax.swing.JTextField();
        BtnGeneratePass = new javax.swing.JButton();
        LblURL = new javax.swing.JLabel();
        TxtURL = new javax.swing.JTextField();
        BtnSave = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtDescription.setMinimumSize(new java.awt.Dimension(37, 225));

        LblDescription.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblDescription.setForeground(new java.awt.Color(0, 0, 0));
        LblDescription.setText("Description:");

        LblUserName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblUserName.setForeground(new java.awt.Color(0, 0, 0));
        LblUserName.setText("Username :");

        TxtUsername.setMinimumSize(new java.awt.Dimension(37, 225));

        LblPassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblPassword.setForeground(new java.awt.Color(0, 0, 0));
        LblPassword.setText("Password :");

        TxtPassword.setEnabled(false);

        BtnGeneratePass.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        BtnGeneratePass.setText("Generate Password");

        LblURL.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblURL.setForeground(new java.awt.Color(0, 0, 0));
        LblURL.setText("URL :");

        BtnSave.setLabel("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BtnCancel.setText("Cancel");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 71, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LblDescription)
                            .addGap(17, 17, 17)
                            .addComponent(TxtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(LblUserName)
                            .addGap(18, 18, 18)
                            .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(LblPassword)
                            .addGap(21, 21, 21)
                            .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(157, 157, 157)
                            .addComponent(BtnGeneratePass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(LblURL)
                            .addGap(25, 25, 25)
                            .addComponent(TxtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(BtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 72, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(LblDescription))
                        .addComponent(TxtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(12, 12, 12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(LblUserName))
                        .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(LblPassword))
                        .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(13, 13, 13)
                    .addComponent(BtnGeneratePass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(13, 13, 13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(LblURL))
                        .addComponent(TxtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // Setting of the required variables
        String Username = TxtUsername.getText();
        String Password = TxtPassword.getText();
        String Description = TxtDescription.getText();
        String URL = TxtURL.getText();
        String UserID = user.getUserID();

        //  Data and query required for editing accounts(delete and create)
        Object[] Accdata = {Description, Username, Password, URL, UserID};
        String insertQuery = "INSERT INTO accounts (Description, Username, Password, URL, user_id) VALUES (?, ?, ?, ?, ?)";
        String deletequery ="DELETE FROM accounts WHERE Description = ? AND user_ID = ?";
        Object[] deleteparam =  {description, user.getUserID()};
        
        //          Data required to check if there are any duplicates
        Object[] Data = {Description, UserID};
        String duplicateQuery = "SELECT Description FROM accounts WHERE Description = ? AND user_id = ?";
        Object [] exclude= {description};
        
        if((Username.equals("") || Password.equals("") || Description.equals("") || URL.equals(""))){
            
             GeneralFunctions.showNotification("Please ensure that all the textboxes are filled in.", "Failed");
        }
        else if (GeneralFunctions.checkDuplicate(Data ,duplicateQuery,exclude) == true) {

            GeneralFunctions.showNotification("There is already an account with the same description.", "Failed");
        } else {

            try {

                DB_Connection connection = new DB_Connection();

                connection.getConnection();

//              Function to delete 
                connection.executeQuery(deletequery, deleteparam);
                 
//              Function to recreatre
                connection.executeQuery(insertQuery, Accdata);

                GeneralFunctions.showNotification("Account edited", "Success");

                Dashboard dashboard = new Dashboard(user);
                dashboard.setVisible(true);

                this.dispose();

            } catch (SQLException ex) {
                Logger.getLogger(RegisterPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed

        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BtnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAccountPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAccountPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAccountPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAccountPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAccountPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnGeneratePass;
    private javax.swing.JButton BtnSave;
    private javax.swing.JLabel LblDescription;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblURL;
    private javax.swing.JLabel LblUserName;
    private javax.swing.JTextField TxtDescription;
    private javax.swing.JTextField TxtPassword;
    private javax.swing.JTextField TxtURL;
    private javax.swing.JTextField TxtUsername;
    // End of variables declaration//GEN-END:variables
}
