package com.mycompany.fypmaven;

import java.awt.Color;
import java.awt.KeyboardFocusManager;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Work
 */
public class RegisterPanel extends javax.swing.JFrame {

    String password;
    String confirmPassword;

    public RegisterPanel() {
        initComponents();
        
        this.password = TxtPassword.getText();
        this.confirmPassword = TxtConfirmPassword.getText();
        
//        Initial setup of the interface
        LblWrongPass.setVisible(false);
        LblPassDetails.setVisible(false);
        LblPassDetailsPt2.setVisible(false);

//        Function to allow remove focus on background click
        getContentPane().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                KeyboardFocusManager.getCurrentKeyboardFocusManager().clearGlobalFocusOwner();
            }
        });

//        Clears the username textbox on focus and fills it back on focus loss
        TxtUsername.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (TxtUsername.getText().equals("Enter your Username")) {
                    TxtUsername.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (TxtUsername.getText().isEmpty()) {
                    TxtUsername.setText("Enter your Username");
                    TxtUsername.setForeground(Color.GRAY);
                }
            }
        });

//         Clears the password textbox on focus and fills it back on focus loss
        TxtPassword.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (TxtPassword.getText().equals("Enter your Password")) {
                    TxtPassword.setText("");
                }

            }

            @Override
            public void focusLost(FocusEvent e) {
                if (TxtPassword.getText().isEmpty()) {
                    TxtPassword.setText("Enter your Password");
                    TxtPassword.setForeground(Color.GRAY);
                }
            }

        });

        //Clears the password textbox on focus and fills it back on focus loss
        TxtConfirmPassword.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {

                if (TxtConfirmPassword.getText().equals("Confirm your Password")) {
                    TxtConfirmPassword.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (TxtConfirmPassword.getText().isEmpty()) {
                    TxtConfirmPassword.setText("Confirm your Password");
                    TxtConfirmPassword.setForeground(Color.GRAY);
                }

            }

        });
        
        
//  DocumentListener for the confirm password field
        TxtConfirmPassword.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                checkPasswords();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                checkPasswords();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                checkPasswords();
            }

            private void checkPasswords() {
                
                if (!password.equals(confirmPassword)) {

                    LblWrongPass.setVisible(true);

                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblUsername = new javax.swing.JLabel();
        LblPassword = new javax.swing.JLabel();
        LblPassDetails = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtPassword = new javax.swing.JTextField();
        TxtConfirmPassword = new javax.swing.JTextField();
        TxtUsername = new javax.swing.JTextField();
        BtnRegister = new javax.swing.JButton();
        LblWrongPass = new javax.swing.JLabel();
        LblPassDetailsPt2 = new javax.swing.JLabel();
        BtnCancel = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        LblUsername.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblUsername.setForeground(new java.awt.Color(0, 0, 0));
        LblUsername.setText("Username");

        LblPassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LblPassword.setForeground(new java.awt.Color(0, 0, 0));
        LblPassword.setText("Password");

        LblPassDetails.setForeground(new java.awt.Color(255, 0, 51));
        LblPassDetails.setText("Please ensure that password has at least 1 upper case letter,");
        LblPassDetails.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Confirm Password");

        TxtPassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TxtPassword.setForeground(new java.awt.Color(0, 0, 0));
        TxtPassword.setText("Enter your Password");

        TxtConfirmPassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TxtConfirmPassword.setForeground(new java.awt.Color(0, 0, 0));
        TxtConfirmPassword.setText("Confirm your Password");

        TxtUsername.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TxtUsername.setForeground(new java.awt.Color(0, 0, 0));
        TxtUsername.setText("Enter your Username");

        BtnRegister.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BtnRegister.setText("Register");
        BtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisterActionPerformed(evt);
            }
        });

        LblWrongPass.setForeground(new java.awt.Color(255, 51, 51));
        LblWrongPass.setText("The passwords entered are not the same");
        LblWrongPass.setFocusable(false);

        LblPassDetailsPt2.setForeground(new java.awt.Color(255, 0, 51));
        LblPassDetailsPt2.setText(" 1 lower case letter, 1 number, and 1 special character ");
        LblPassDetailsPt2.setFocusable(false);

        BtnCancel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BtnCancel.setText("Cancel");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(LblUsername)
                        .addGap(76, 76, 76)
                        .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(LblPassword)
                        .addGap(79, 79, 79)
                        .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(LblPassDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(LblPassDetailsPt2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(TxtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(LblWrongPass))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(BtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(LblUsername))
                    .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(LblPassword))
                    .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(LblPassDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(LblPassDetailsPt2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(LblWrongPass)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisterActionPerformed
         // setting of variables
        String Username = TxtUsername.getText();
        String Password = TxtPassword.getText();
        
        
        if (!password.equals(confirmPassword)) {
            
        }else{

            //  if statement to register the account
        if (GeneralFunctions.isValidPassword(Password)) {

            Object[] Data = {Username};
            String duplicateQuery =  "SELECT Name FROM user_accounts WHERE Name = ?";
            
            if (GeneralFunctions.checkDuplicate(Data,duplicateQuery) == true) {

            GeneralFunctions.showNotification("There is already an user with that username.", "Failed");

        } else {
            UserAccs user = new UserAccs(Username,Password);
            
            this.dispose();
            RecoveryPhrase recovery = new RecoveryPhrase(user);
            recovery.setVisible(true);
            }
        } else {

            LblPassDetails.setVisible(true);
            LblPassDetailsPt2.setVisible(true);

        }
        }
    }//GEN-LAST:event_BtnRegisterActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
         this.dispose();
         
        LoginPanel login = new LoginPanel();
        login.setVisible(true);
    }//GEN-LAST:event_BtnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnRegister;
    private javax.swing.JLabel LblPassDetails;
    private javax.swing.JLabel LblPassDetailsPt2;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblUsername;
    private javax.swing.JLabel LblWrongPass;
    private javax.swing.JTextField TxtConfirmPassword;
    private javax.swing.JTextField TxtPassword;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
